// Generated by tools/generate-dbus-client.mjs from data/com.timokuehne.MeetingRecorder1.xml.
// Do not edit this file by hand.

import Gio from "gi://Gio";
import GLib from "gi://GLib";

export const BUS_NAME = "com.timokuehne.MeetingRecorder1";
export const OBJECT_PATH = "/com/timokuehne/MeetingRecorder1";

export type GetStatusResult = {
	recording: boolean;
	file: string;
	startedAt: string;
	message: string;
};

export type StartRecordingResult = {
	file: string;
	startedAt: string;
};

export type TranscribeResult = {
	transcriptFile: string;
	postTranscribeHookError: string;
};

export class MeetingRecorderClient {
	private constructor(private readonly _proxy: Gio.DBusProxy) {}

	static connect(cancellable: Gio.Cancellable | null = null): Promise<MeetingRecorderClient> {
		return new Promise((resolve, reject) => {
			Gio.DBusProxy.new_for_bus(
				Gio.BusType.SESSION,
				Gio.DBusProxyFlags.NONE,
				null,
				BUS_NAME,
				OBJECT_PATH,
				BUS_NAME,
				cancellable,
				(_source, result) => {
					try {
						resolve(
							new MeetingRecorderClient(Gio.DBusProxy.new_for_bus_finish(result)),
						);
					} catch (error) {
						reject(error);
					}
				},
			);
		});
	}

	get available(): boolean {
		return this._proxy.get_name_owner() !== null;
	}

	get browserAudioCapture(): boolean {
		return readCachedBoolean(this._proxy, "BrowserAudioCapture");
	}

	get browserVideoCapture(): boolean {
		return readCachedBoolean(this._proxy, "BrowserVideoCapture");
	}

	get recording(): boolean {
		return readCachedBoolean(this._proxy, "Recording");
	}

	get recordingFile(): string {
		return readCachedString(this._proxy, "RecordingFile");
	}

	get startedAt(): string {
		return readCachedString(this._proxy, "StartedAt");
	}

	connectPropertiesChanged(handler: () => void): number {
		return this._proxy.connect("g-properties-changed", handler);
	}

	connectAvailabilityChanged(handler: () => void): number {
		return this._proxy.connect("notify::g-name-owner", handler);
	}

	connectTranscriptionCompleted(
		handler: (
			audioFile: string,
			transcriptFile: string,
			postTranscribeHookError: string,
		) => void,
	): number {
		return this._proxy.connect("g-signal", (_proxy, _sender, signalName, parameters) => {
			if (signalName !== "TranscriptionCompleted") return;

			expectTuple(parameters, "(sss)", "TranscriptionCompleted");
			handler(
				readString(parameters, 0),
				readString(parameters, 1),
				readString(parameters, 2),
			);
		});
	}

	connectTranscriptionFailed(handler: (audioFile: string, message: string) => void): number {
		return this._proxy.connect("g-signal", (_proxy, _sender, signalName, parameters) => {
			if (signalName !== "TranscriptionFailed") return;

			expectTuple(parameters, "(ss)", "TranscriptionFailed");
			handler(readString(parameters, 0), readString(parameters, 1));
		});
	}

	disconnect(signalId: number): void {
		this._proxy.disconnect(signalId);
	}

	async getStatus(cancellable: Gio.Cancellable | null = null): Promise<GetStatusResult> {
		const reply = await this._call("GetStatus", new GLib.Variant("()", []), -1, cancellable);
		expectTuple(reply, "(bsss)", "GetStatus");
		return {
			recording: readBoolean(reply, 0),
			file: readString(reply, 1),
			startedAt: readString(reply, 2),
			message: readString(reply, 3),
		};
	}

	async startRecording(
		cancellable: Gio.Cancellable | null = null,
	): Promise<StartRecordingResult> {
		const reply = await this._call(
			"StartRecording",
			new GLib.Variant("()", []),
			-1,
			cancellable,
		);
		expectTuple(reply, "(ss)", "StartRecording");
		return {
			file: readString(reply, 0),
			startedAt: readString(reply, 1),
		};
	}

	async stopRecording(cancellable: Gio.Cancellable | null = null): Promise<string> {
		const reply = await this._call(
			"StopRecording",
			new GLib.Variant("()", []),
			-1,
			cancellable,
		);
		expectTuple(reply, "(s)", "StopRecording");
		return readString(reply, 0);
	}

	async transcribe(
		audioFile: string,
		provider: string,
		language: string,
		format: boolean,
		multichannel: boolean,
		output: string,
		cancellable: Gio.Cancellable | null = null,
	): Promise<TranscribeResult> {
		const reply = await this._call(
			"Transcribe",
			new GLib.Variant("(sssbbs)", [
				audioFile,
				provider,
				language,
				format,
				multichannel,
				output,
			]),
			GLib.MAXINT32,
			cancellable,
		);
		expectTuple(reply, "(ss)", "Transcribe");
		return {
			transcriptFile: readString(reply, 0),
			postTranscribeHookError: readString(reply, 1),
		};
	}

	async getApiKeyStatus(
		provider: string,
		cancellable: Gio.Cancellable | null = null,
	): Promise<boolean> {
		const reply = await this._call(
			"GetApiKeyStatus",
			new GLib.Variant("(s)", [provider]),
			-1,
			cancellable,
		);
		expectTuple(reply, "(b)", "GetApiKeyStatus");
		return readBoolean(reply, 0);
	}

	async setApiKey(
		provider: string,
		apiKey: string,
		cancellable: Gio.Cancellable | null = null,
	): Promise<void> {
		const reply = await this._callWithSecret(
			"SetApiKey",
			(handle) => new GLib.Variant("(sh)", [provider, handle]),
			apiKey,
			cancellable,
		);
		expectTuple(reply, "()", "SetApiKey");
		return;
	}

	async deleteApiKey(
		provider: string,
		cancellable: Gio.Cancellable | null = null,
	): Promise<void> {
		const reply = await this._call(
			"DeleteApiKey",
			new GLib.Variant("(s)", [provider]),
			-1,
			cancellable,
		);
		expectTuple(reply, "()", "DeleteApiKey");
		return;
	}

	private _call(
		method: string,
		parameters: GLib.Variant,
		timeout: number,
		cancellable: Gio.Cancellable | null,
	): Promise<GLib.Variant> {
		return new Promise((resolve, reject) => {
			this._proxy.call(
				method,
				parameters,
				Gio.DBusCallFlags.NONE,
				timeout,
				cancellable,
				(_source, result) => {
					try {
						resolve(this._proxy.call_finish(result));
					} catch (error) {
						reject(error);
					}
				},
			);
		});
	}

	private async _callWithSecret(
		method: string,
		parametersForHandle: (handle: number) => GLib.Variant,
		secret: string,
		cancellable: Gio.Cancellable | null,
	): Promise<GLib.Variant> {
		const [reader, writer] = createSocketPair();
		const descriptorList = Gio.UnixFDList.new();
		const handle = descriptorList.append(reader.get_fd());
		reader.close();

		const call = this._callWithFileDescriptors(
			method,
			parametersForHandle(handle),
			descriptorList,
			cancellable,
		);
		let writeError: Error | null = null;
		try {
			writeSecret(writer, secret, cancellable);
		} catch (error) {
			writeError = error instanceof Error ? error : new Error(String(error));
		}
		const reply = await call;
		if (writeError) throw writeError;
		return reply;
	}

	private _callWithFileDescriptors(
		method: string,
		parameters: GLib.Variant,
		descriptors: Gio.UnixFDList,
		cancellable: Gio.Cancellable | null,
	): Promise<GLib.Variant> {
		return new Promise((resolve, reject) => {
			this._proxy.call_with_unix_fd_list(
				method,
				parameters,
				Gio.DBusCallFlags.NONE,
				-1,
				descriptors,
				cancellable,
				(_source, result) => {
					try {
						const [reply] = this._proxy.call_with_unix_fd_list_finish(result);
						resolve(reply);
					} catch (error) {
						reject(error);
					}
				},
			);
		});
	}
}

function createSocketPair(): [Gio.Socket, Gio.Socket] {
	if (!Gio.UnixSocketAddress.abstract_names_supported())
		throw new Error("Unix abstract sockets are unavailable");

	const name = Array.from(new TextEncoder().encode(`heimdall-${GLib.uuid_string_random()}`));
	const address = Gio.UnixSocketAddress.new_abstract(name);
	const listener = Gio.Socket.new(
		Gio.SocketFamily.UNIX,
		Gio.SocketType.STREAM,
		Gio.SocketProtocol.DEFAULT,
	);
	let writer: Gio.Socket | null = null;
	try {
		listener.bind(address, false);
		listener.listen();
		writer = Gio.Socket.new(
			Gio.SocketFamily.UNIX,
			Gio.SocketType.STREAM,
			Gio.SocketProtocol.DEFAULT,
		);
		writer.connect(address, null);
		return [listener.accept(null), writer];
	} catch (error) {
		writer?.close();
		throw error;
	} finally {
		listener.close();
	}
}

function writeSecret(writer: Gio.Socket, value: string, cancellable: Gio.Cancellable | null): void {
	const bytes = new TextEncoder().encode(value);
	if (bytes.length > 64 * 1024) throw new Error("API key exceeds the 64 KiB limit");

	try {
		let offset = 0;
		while (offset < bytes.length) {
			const written = writer.send(bytes.subarray(offset), cancellable);
			if (written <= 0) throw new Error("Failed to write API key to Unix socket");
			offset += written;
		}
	} finally {
		writer.close();
	}
}

function expectTuple(value: GLib.Variant, signature: string, member: string): void {
	if (value.get_type_string() !== signature)
		throw new Error(`Invalid D-Bus response for ${member}: expected ${signature}`);
}

function child(value: GLib.Variant, index: number): GLib.Variant {
	return value.get_child_value(index);
}

function readBoolean(value: GLib.Variant, index: number): boolean {
	return child(value, index).get_boolean();
}

function readString(value: GLib.Variant, index: number): string {
	return child(value, index).get_string()[0];
}

function readCachedBoolean(proxy: Gio.DBusProxy, property: string): boolean {
	const value = proxy.get_cached_property(property);
	if (!value || value.get_type_string() !== "b")
		throw new Error(`D-Bus property ${property} is unavailable`);
	return value.get_boolean();
}

function readCachedString(proxy: Gio.DBusProxy, property: string): string {
	const value = proxy.get_cached_property(property);
	if (!value || value.get_type_string() !== "s")
		throw new Error(`D-Bus property ${property} is unavailable`);
	return value.get_string()[0];
}
